In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.3'

In [3]:
data1 = [1,2,3]
data1

[1, 2, 3]

In [5]:
data2 = [1,2,3,3.5,5]
data2

[1, 2, 3, 3.5, 5]

In [6]:
arr1 = np.array(data1)
arr1

array([1, 2, 3])

In [7]:
(arr1.dtype,arr1.shape)

(dtype('int64'), (3,))

# 1. numpy 자료형
## float : 실수

In [10]:
arr2 = np.array([1,2,3,3.5,5])
arr2,arr2.dtype,arr2.shape

(array([1. , 2. , 3. , 3.5, 5. ]), dtype('float64'), (5,))

## int : 정수

In [15]:
arr3 = np.array([1,2,3,4,5])
arr3,arr3.dtype,arr3.shape

(array([1, 2, 3, 4, 5]), dtype('int64'), (5,))

In [18]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4,arr4.dtype,arr4.shape

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 dtype('int64'),
 (4, 3))

## complex : 복소수

In [20]:
arr5 = np.array([5+2j])
arr5,arr5.dtype,arr5.shape

(array([5.+2.j]), dtype('complex128'), (1,))

## bool : 불리언

In [21]:
arr6 = np.array([True])
arr6,arr6.dtype,arr6.shape

(array([ True]), dtype('bool'), (1,))

## string : 문자열

In [22]:
arr7 = np.array(['a'])
arr7,arr7.dtype,arr7.shape

(array(['a'], dtype='<U1'), dtype('<U1'), (1,))

## object : 파이썬 오브젝트

In [33]:
arr8 = np.array([1, 0.1, 'one!'], dtype=object)

arr8,arr8.dtype,arr8.shape

(array([1, 0.1, 'one!'], dtype=object), dtype('O'), (3,))

In [34]:
arr8[0]

1

In [35]:
arr8[1],arr8[2]

(0.1, 'one!')

In [36]:
arr8 *2

array([2, 0.2, 'one!one!'], dtype=object)

---
# 2. arange (start,end,step)(정수)

In [37]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [40]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

---
# 3. linspace(start,stop,num=50)(실수)

In [41]:
np.linspace(1,10,10) #1부터 10까지 10개

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [45]:
np.linspace(1,100,5) #1부터 100까지 5개

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

---

# 4. 특별한 형태의 배열 생성
## 1) np.zeros(shape,dtype=float)

In [46]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
np.zeros((4,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [50]:
np.zeros((4,2)).reshape(2,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 2) np.ones(shape,dtype=float)

In [51]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
np.ones((5,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

## 3) np.eye(n,m,k=K,dtype=float) #대각요소 1

In [53]:
np.eye(2,5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

In [54]:
np.eye(3,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [55]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
np.eye(4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## 4) np.identity(n,dtype=float) #대각요소 1

In [57]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## 5) np.empty(shape,dtype=float) #초기화 되지 않은 배열

In [59]:
np.empty(5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [70]:
np.empty(4, dtype=int)

array([4607182418800017408, 4607182418800017408, 4607182418800017408,
       4607182418800017408])

---
# 5. 데이터 타입 변환 : astype() 함수

## 1) 데이터 형식 모음

### 1. 'i' : 부호가 있는 정수 int(8,16,32,64)
### 2. 'u' : 부호가 없는 정수 uint(8,16,32,64) 
### 3. 'f' : 실수 float(16,32,64,128)
### 4. 'c' : 복소수 complex(64,128,256)
### 5. 'b' : 불리언 bool
### 6. 'S'/'a' : 문자열 String_
### 7. 'O' : 파이썬 오브젝트 object
### 8. 'U' : 유니코드 unicode_
### 9. 'M' : 날짜 datetime

## 2) 문자열 배열 -> 숫자형 배열

In [71]:
str1 = np.array(['1.5','0.62','2','3.14','3.141592'])
str1

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [72]:
num1 = str1.astype(float)
num1

array([1.5     , 0.62    , 2.      , 3.14    , 3.141592])

## 3) 실수형 배열 -> 정수형 배열

In [73]:
numf = np.array([10,21,0.549,4.75,5.98])
numf

array([10.   , 21.   ,  0.549,  4.75 ,  5.98 ])

In [74]:
numi = numf.astype(int)
numi, numi.dtype

(array([10, 21,  0,  4,  5]), dtype('int64'))

## 4) 숫자형 배열 -> 문자형 배열

In [75]:
numf.astype('U')

array(['10.0', '21.0', '0.549', '4.75', '5.98'], dtype='<U32')

In [76]:
numi.astype('S')

array([b'10', b'21', b'0', b'4', b'5'], dtype='|S21')

---
# 6. 난수 배열

## 1) random.rand([d0, d1,...,dn])(실수)

In [77]:
np.random.rand(10)

array([7.22284553e-01, 4.76956410e-02, 3.23495390e-01, 7.07763924e-01,
       7.03910905e-01, 1.02091887e-01, 4.94007189e-01, 7.21485140e-01,
       4.50543753e-04, 7.21448684e-01])

In [78]:
np.random.rand(2,5)

array([[0.72644158, 0.89030507, 0.57594377, 0.56526431, 0.34155381],
       [0.71805501, 0.20973023, 0.36435134, 0.74938855, 0.19409927]])

In [79]:
np.random.rand(2,3,4)

array([[[0.83900541, 0.46164257, 0.97289911, 0.48929248],
        [0.36891446, 0.54639295, 0.35612914, 0.16077698],
        [0.46522856, 0.52948483, 0.29653611, 0.57831003]],

       [[0.36226732, 0.86163887, 0.15114247, 0.67173504],
        [0.34068759, 0.60180207, 0.91637989, 0.10213508],
        [0.73949309, 0.73381806, 0.52760215, 0.82976519]]])

In [80]:
np.random.rand(2,3,4,5)

array([[[[0.2205113 , 0.29568044, 0.28910466, 0.05402562, 0.57859783],
         [0.424811  , 0.41063803, 0.42164402, 0.02734786, 0.44007326],
         [0.47761605, 0.2739387 , 0.13757604, 0.56964941, 0.73843779],
         [0.42830519, 0.64735679, 0.64813313, 0.35463407, 0.10841718]],

        [[0.00924213, 0.79198991, 0.0342641 , 0.89225064, 0.65988282],
         [0.16123248, 0.47213816, 0.51580081, 0.75682897, 0.64853354],
         [0.43144296, 0.89456342, 0.03863735, 0.60314367, 0.31350714],
         [0.2447092 , 0.1997654 , 0.78873833, 0.92091016, 0.49069295]],

        [[0.21711752, 0.93916994, 0.76580012, 0.83770506, 0.6184003 ],
         [0.20388486, 0.63319047, 0.22759396, 0.98053289, 0.8221736 ],
         [0.64886957, 0.21771402, 0.86552432, 0.29640234, 0.95048144],
         [0.6436856 , 0.95765039, 0.7034945 , 0.21850192, 0.20000586]]],


       [[[0.09692214, 0.63178621, 0.84353004, 0.07388363, 0.01701406],
         [0.24845584, 0.45174564, 0.35856256, 0.18654354, 0.71306827]

## 2) random.randint([low,] high [,size])(정수)

In [81]:
np.random.randint(10)

1

In [82]:
np.random.randint(10,20)

18

In [83]:
np.random.randint(10,20,size=(3))

array([13, 13, 14])

In [84]:
np.random.randint(1,10,size=9)

array([9, 1, 9, 6, 4, 6, 3, 9, 9])