# 0107_3_Numpy 인덱싱과 슬라이싱
> 3. Array 인덱싱(indexing)과 슬라이싱(Slicing)

# 3. Array 인덱싱(indexing)과 슬라이싱(Slicing)
- 인덱싱(indexing) : 배열의 위치나 조건을 지정해 배열의 원소를 선택하는 것
- 슬라이싱(Slicing) : 범위를 지정해 배열의 원소를 선택하는 것

## A) 1차원 배열의 인덱싱
###  1.       배열명[위치]
   - 파이썬의 인덱싱과 동일 
   - 0번째로 시작함

In [2]:
import numpy as np

In [3]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 0번째 요소
arr1[0]

0

In [5]:
# 3번째 요소
arr1[3]

3

### 2. 배열명[[위치1, 위치2, ... , 위치n]]

- shape 
    - (m, ) : 1차원
    - (m,n) : 2차원
    - (m,n,p) : 3차원  


- 인덱스[] 
    - [ m] : 1차원
    - [m,n] : 2차원
    - [m,n,p] : 3차원


In [6]:
# 1,3,4번째 요소 
# arr1[[1,3,4]] => 3차원 배열의 위치 1면 3행 4열
# 여러 인덱스의 요소들을 지정할 때는 리스트로 줘야 한다.
arr1[[1,3,4]]

array([1, 3, 4])

## B) 2차원 배열의 인덱싱
### 1. 배열명[행위치, 열위치]

In [7]:
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
# 2차원의 array에서 인덱싱을 하기 위해선 2개의 인자를 입력해야 합니다.
arr2[2,3] #2행 3열의 요소 => 3,4

12

In [9]:
# 0행 0열의 값 변경
arr2[0,0] = 90
arr2[0,0]

90

In [10]:
# 변경 확인
arr2

array([[90,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 2. 2차원배열명[행위치]
: 2차원 배열에서 지정한 행 전체가 선택됨

In [11]:
# 두번째 행(1행) 선택
arr2[1]

array([5, 6, 7, 8])

### 3. 2차원배열명[ : , 열위치]
: 2차원 배열에서 지정한 열 전체가 선택됨

In [12]:
# 두번째 열(1열) 선택
arr2[:,1]

array([ 2,  6, 10])

### 4. 2차원 배열의 특정 행을 지정해서 행 전체를 변경 

In [13]:
# 두번째 행 변경
arr2[1] = np.array([50,-60,70,-80])

In [14]:
# 변경 확인
arr2

array([[ 90,   2,   3,   4],
       [ 50, -60,  70, -80],
       [  9,  10,  11,  12]])

### 5. 배열명[[ 행위치1, 행위치2, ..., 행위치n],[열위치1, 열위치2, ..., 열위치n]]
: 지정한 (행위치1, 열위치1), (행위치2, 열위치2), ..., (행위치n, 열위치n)

In [15]:
arr2[[0,2],[0,1]] #0행,2행에서 0열,1열을 가져옴 (0,0),(2,1)

array([90, 10])

In [16]:
arr2

array([[ 90,   2,   3,   4],
       [ 50, -60,  70, -80],
       [  9,  10,  11,  12]])

### 6.배열명[조건]
: 배열에서 조건을 만족하는 원소만 선택

- 10이상인 원소 선택

In [17]:
arr2 > 10

array([[ True, False, False, False],
       [ True, False,  True, False],
       [False, False,  True,  True]])

In [18]:
arr2[arr2>10] # 10 이상인 것들만 가져와서 리스트로 

array([90, 50, 70, 11, 12])

- 짝수인 원소 선택

In [19]:
# 짝수인 원소 선택
arr2[arr2 % 2 == 0]

array([ 90,   2,   4,  50, -60,  70, -80,  10,  12])

## C) 1차원 배열의 슬라이싱(Slicing)
### 1. 배열[시작위치 : 끝위치]
: 시작위치에서 끝위치-1에 해당하는 배열의 원소를 반환

In [20]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# 3번째 요소부터 8번째 요소
arr1[3:9] # end+1

array([3, 4, 5, 6, 7, 8])

### 2. 배열명[start:end+1:step] 
: start에서 end 범위까지의 자료중 step 간격의 인덱스 지정

In [22]:
# 3번째 요소부터 8번째 요소까지 step 2
arr1[3:9:2]

array([3, 5, 7])

In [23]:
# 0번째 요소부터 8번째 요소까지 step 2
arr1[:9:2] 

array([0, 2, 4, 6, 8])

In [24]:
# 3번째 요소부터 마지막 요소까지 step 2
arr1[3::2]

array([3, 5, 7, 9])

In [25]:
# 0번째 요소부터 마지막 요소까지 step 3
arr1[::3]

array([0, 3, 6, 9])

In [26]:
# 0번째 요소부터 마지막 요소까지 거꾸로
arr1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [27]:
# 0번째 요소부터 마지막 요소까지 거꾸로 step 2
arr1[::-2]

array([9, 7, 5, 3, 1])

### 3. 배열[끝위치]
: 처음부터 '끝위치-1' 원소 반환

In [28]:
arr1[:3]

array([0, 1, 2])

### 4. 배열[시작위치:]
: 처음부터 마지막 원소까지 반환

In [29]:
arr1[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

### 5. 배열[:]
: 모든 원소 반환

In [30]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 6. 배열[행시작위치: 행끝위치, 열시작위치:열끝위치]

In [31]:
arr2

array([[ 90,   2,   3,   4],
       [ 50, -60,  70, -80],
       [  9,  10,  11,  12]])

In [32]:
# 2행의 모든 요소 꺼내기
arr2[2,:] # == arr2[2]

array([ 9, 10, 11, 12])

In [33]:
# 3열의 모든 요소 꺼내기
arr2[:,3]

array([  4, -80,  12])

In [34]:
# 1~2행, 1~2열의 요소
arr2[1:3,1:3]

array([[-60,  70],
       [ 10,  11]])

### 7. 배열[행위치][열시작위치:열끝위치]
: 특정 행을 선택한 후 열을 슬라이싱

In [35]:
arr3 = np.arange(10,100,10).reshape(3,3)
arr3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [36]:
# 1행의 (0열과 1열) 요소 선택
# 방법 1.
arr3[1,:2]

array([40, 50])

In [37]:
# 방법 2.
arr3[1][:2]

array([40, 50])

In [38]:
arr3[2][1] 

80

### 8. 슬라이싱된 배열에 값을 지정

In [39]:
# 0~1행, 1~2열의 요소 변경
arr3,arr3[:2,1:3],arr3[0][1:3],arr3[1][1:3]

(array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]),
 array([[20, 30],
        [50, 60]]),
 array([20, 30]),
 array([50, 60]))

In [40]:
arr3[:2,1:3] = np.array([[1,2],[3,4]])
arr3

array([[10,  1,  2],
       [40,  3,  4],
       [70, 80, 90]])

## D) Array boolean 인덱싱 (Mask)
- 다차원의 인덱싱을 응용하여 boolean 인덱싱
- boolean 인덱싱을 통해 만들어낸 array를 통해 원하는 행 또는 열의 값만 뽑아냄
- 가리고 싶은 부분은 가리고, 원하는 요소만 꺼냄

In [42]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [43]:
# names 크기 확인
# names.size
names.shape

(8,)

In [44]:
# 8행 4열의 실수 난수 배열 생성
data = np.random.randn(8,4)
data

array([[-2.01133057, -0.83120468, -1.20457008,  1.79512961],
       [-0.55937897,  1.09484195,  0.21007492,  0.84312094],
       [-0.44648162, -0.03874274,  0.14515349,  0.40167187],
       [ 0.02438302, -0.51498839,  1.87589906,  0.05588363],
       [-0.11903061, -0.49806042,  1.03685879, -0.02828617],
       [ 0.69171869,  0.47195583, -1.08653881, -0.32793567],
       [-0.5646625 , -1.40842561, -0.86766609, -0.09684767],
       [ 0.97897538, -0.36071289, -0.57494245, -0.76098392]])

In [45]:
# 배열 크기 확인
data.shape

(8, 4)

In [46]:
# 요소가 Beomwoo인 항목에 대한 mask 생성
names == 'Beomwoo'

array([ True,  True, False, False, False,  True, False,  True])

In [47]:
names_mask_BW = (names == 'Beomwoo')
names_mask_BW

array([ True,  True, False, False, False,  True, False,  True])

In [48]:
# 요소가 Beomwoo인 항목의 위치와 같은 행의 자료 가져오기 
data[names_mask_BW, :] # ==data[names_mask_BW]

array([[-2.01133057, -0.83120468, -1.20457008,  1.79512961],
       [-0.55937897,  1.09484195,  0.21007492,  0.84312094],
       [ 0.69171869,  0.47195583, -1.08653881, -0.32793567],
       [ 0.97897538, -0.36071289, -0.57494245, -0.76098392]])

In [49]:
# 요소가 Kim인 행의 데이터만 꺼내기
names_mask_K = (names == 'Kim')
names_mask_K

array([False, False,  True, False, False, False, False, False])

In [50]:
# 방법 1
data[names_mask_K]

array([[-0.44648162, -0.03874274,  0.14515349,  0.40167187]])

In [51]:
# 방법 2
data[names=='Kim', :]

array([[-0.44648162, -0.03874274,  0.14515349,  0.40167187]])

In [52]:
# 논리 연산을 응용하여, 요소가 Kim 또는 Park인 행의 데이터만 꺼내기
data[(names == 'kim') | (names == 'Park')]

array([[-0.5646625 , -1.40842561, -0.86766609, -0.09684767]])

 ### 1) 마스크 인덱싱 문제
 - 문제1. data array에서 0번째 열이 0보다 작은 행 데이터 가져오기

In [53]:
# 1단계. 마스크를 만든다
#       data array에서 0번째 열이 0보다 작은 요소의 
#       boolean 값을 선택하기 위한 마스크
data

array([[-2.01133057, -0.83120468, -1.20457008,  1.79512961],
       [-0.55937897,  1.09484195,  0.21007492,  0.84312094],
       [-0.44648162, -0.03874274,  0.14515349,  0.40167187],
       [ 0.02438302, -0.51498839,  1.87589906,  0.05588363],
       [-0.11903061, -0.49806042,  1.03685879, -0.02828617],
       [ 0.69171869,  0.47195583, -1.08653881, -0.32793567],
       [-0.5646625 , -1.40842561, -0.86766609, -0.09684767],
       [ 0.97897538, -0.36071289, -0.57494245, -0.76098392]])

In [54]:
data[data[:,0] < 0]

array([[-2.01133057, -0.83120468, -1.20457008,  1.79512961],
       [-0.55937897,  1.09484195,  0.21007492,  0.84312094],
       [-0.44648162, -0.03874274,  0.14515349,  0.40167187],
       [-0.11903061, -0.49806042,  1.03685879, -0.02828617],
       [-0.5646625 , -1.40842561, -0.86766609, -0.09684767]])

- 문제2. data array에서 0번째 열이 0보다 작은 행의 2,3번째 열 데이터 가져오기

In [55]:
# 1. 마스크 생성 : 0번째 열의 값이 0보다 작은 행의 2,3번째 열 값
data[data[:,0]<0][:,2:4],data[data[:,0]<0,2:4]

(array([[-1.20457008,  1.79512961],
        [ 0.21007492,  0.84312094],
        [ 0.14515349,  0.40167187],
        [ 1.03685879, -0.02828617],
        [-0.86766609, -0.09684767]]),
 array([[-1.20457008,  1.79512961],
        [ 0.21007492,  0.84312094],
        [ 0.14515349,  0.40167187],
        [ 1.03685879, -0.02828617],
        [-0.86766609, -0.09684767]]))

In [56]:
mask = data[:,0] <0
mask

array([ True,  True,  True, False,  True, False,  True, False])

In [57]:
# 2. 생성된 마스크로 데이터 가져오기
data[mask,2:4]

array([[-1.20457008,  1.79512961],
       [ 0.21007492,  0.84312094],
       [ 0.14515349,  0.40167187],
       [ 1.03685879, -0.02828617],
       [-0.86766609, -0.09684767]])